SELECT a.CART_ID
FROM 
(SELECT CART_ID,name
FROM CART_PRODUCTS 
WHERE NAME ='Milk') as a join 
(SELECT CART_ID,name
FROM CART_PRODUCTS 
WHERE NAME ='yogurt')as b 

ON a.CART_ID = b.CART_ID
GROUP BY a.CART_ID
ORDER BY a.CART_ID
